language: rust
jobs:
  include:
    - stage: test
      os: linux
      script:
        - rustup toolchain install nightly
        - rustup component add --toolchain=nightly clippy-preview
        - cargo +nightly clippy
        - cargo build --verbose
        - cargo test --verbose
    - 
      os: osx
      script:
        - rustup toolchain install nightly
        - rustup component add --toolchain=nightly clippy-preview
        - cargo +nightly clippy
        - cargo build --verbose
        - cargo test --verbose
    - stage: deploy
      os:
        - linux
      script: 
        - |
          [ $TRAVIS_BRANCH = master ] &&
          [ $TRAVIS_PULL_REQUEST = false ] &&
          cargo doc --all --no-deps &&
          echo '<meta http-equiv=refresh content=0;url=vst/index.html>' > target/doc/index.html &&
          sudo pip install ghp-import &&
          ghp-import -n target/doc &&
          git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
