[package]
name = "vst2"
version = "0.0.1"
authors = ["Marko Mijalkovic <marko.mijalkovic97@gmail.com>"]

[dependencies]
log = "*"
num = "*"
libc = "*"
dylib = { git="https://github.com/Earlz/rust-dylib" } # For hosts
bitflags = "0.4.0"
