[package]
name = "dimension_expander"
version = "0.1.0"
authors = ["Marko Mijalkovic <marko.mijalkovic97@gmail.com>"]

[dependencies]
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2" }
time = "0.1"

[lib]
name = "dimension_expander"
crate-type = ["dylib"]
